before:
  hooks:
    - GO111MODULE=on go get github.com/google/ko/cmd/ko
    - ko resolve --tags $(basename "${{ .Tag }}" ) -BRf config/ > release.yaml
builds:
- env:
  - CGO_ENABLED=0
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archives:
  - id: ko-release
    name: release.yaml
    format: binary
    files:
    - release.yaml
release:
  name_template: Release {{ .Tag }}
  draft: false
  prerelease: true
  # remove subsequent lines before merging
  github:
    owner: fbiville
    name: sources-for-knative
